config/routes.rb
Taotie::Application.routes.draw do

  put 'likes/:id' => 'likes#update', as: 'like'
  put 'cookbook_likes/:id' => 'cookbook_likes#update', as: 'cookbook_like'

  resources :restaurants

  get 'about' => 'welcome#about'

  resources :menus

  resources :materials

  resources :cookbooks do
    resources :cookbook_comments
  end

  resources :foods do
    resources :comments
  end

  resources :users

  get 'signup' => 'users#new', as: 'signup'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  post 'sessions' => 'sessions#create'
  delete 'sessions/:id' => 'sessions#destroy'

  root :to => 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :food
  attr_accessible :content, :user, :food
  validates_presence_of :content
  validates :content, length: {minimum: 10}
  validates :content, format: { without: /fuck/ }

end

app/models/cook_step.rb
class CookStep < ActiveRecord::Base
  belongs_to :cookbook
  attr_accessible :description, :image_url
end

app/models/cookbook.rb
class Cookbook < ActiveRecord::Base
  attr_accessible :description, :difficulty_level, :time_level, :tips, :user, :food_id
  belongs_to :user
  belongs_to :food
  has_many :cook_steps
  has_many :materials
  has_many :menu_cookbookships
  has_many :menus, through: :menu_cookbookships

  has_one :cookbook_like
  has_many :cookbook_comments

	validates_presence_of :description
  validates_presence_of :difficulty_level
  validates_presence_of :time_level
end

app/models/cookbook_comment.rb
class CookbookComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :cookbook
  attr_accessible :content, :user, :cookbook
  validates_presence_of :content
  validates :content, length: {minimum: 10}
  validates :content, format: { without: /fuck/ }

end

app/models/cookbook_like.rb
class CookbookLike < ActiveRecord::Base
  belongs_to :cookbook
  attr_accessible :count, :cookbook
  has_many :user_cookbook_likeships
  has_many :users, through: :user_cookbook_likeships
end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name, :description, :image_url, :main_user, :detail

  belongs_to :main_user, class_name: 'User', foreign_key: 'main_user_id'

  has_many :user_foodships
  has_many :users, through: :user_foodships

  has_many :food_food_categoryships
  has_many :food_categories, through: :food_food_categoryships

  has_one :like
  has_many :comments
  #image_url
  validates :image_url, allow_blank: true, format: {
    with: /\.(gif|jpg|png|Png|Gif|Jpg)$/,
    message: 'Invalid'}

  validates_presence_of :name
  validates_presence_of :description
end

app/models/food_category.rb
class FoodCategory < ActiveRecord::Base
  attr_accessible :name, :category_id

  validates :name, length: {maximum: 10}

  has_many :food_food_categoryships
  has_many :foods, through: :food_food_categoryships
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :food
  has_many :user_likeships
  has_many :users, through: :user_likeships
  attr_accessible :count, :food
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :cookbook
  attr_accessible :name, :quantity
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :user
  has_many :menu_cookbookships
  has_many :cookbooks, through: :menu_cookbookships
  attr_accessible :description, :name
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :name, :user, :image_url
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation,:image_url, :description
  #email
  validates_uniqueness_of :email
  validates :email, format: {
    with: /^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/,
    message: 'Invalid'}
  #name
  validates_presence_of :name, :email
  validates_uniqueness_of :name
  #password
  validates_presence_of :password_confirmation
  validates_confirmation_of :password, on: :create
  validates_presence_of :password, on: :create
  validates :password, length: {minimum: 6}
  #image_url
  validates :image_url, format: {
    with: /\.(gif|jpg|png|Png|Gif|Jpg)$/,
    message: 'Invalid'}

  def self.authenticate(email, password)
    user = find_by_email_and_password(email, password)
  end
  #food posted by the user
  has_many :user_foodships
  has_many :foods, through: :user_foodships
  #like liked by the user
  has_many :user_likeships
  has_many :likes, through: :user_likeships
  #cookbook_like liked by the user
  has_many :user_cookbook_likeships
  has_many :cookbook_likes, through: :user_cookbook_likeships
  #
  def able_to_modify_food?(food)
    self.foods.find(:all, conditions: ['food_id = ?', food.id]).size != 0
  end
  #
  def already_likes?(food)
    self.likes.find(:all, conditions: ['food_id = ?', food.id]).size != 0
  end
  #
  def already_likes_cookbook?(cookbook)
    self.cookbook_likes.find(:all, conditions: ['cookbook_id = ?', cookbook.id]).size != 0
  end
end

app/models/user_foodship.rb
class UserFoodship < ActiveRecord::Base
  attr_accessible :food, :user
  attr_accessible :food_id, :user_id
  belongs_to :food
  belongs_to :user
end

app/models/user_likeship.rb
class UserLikeship < ActiveRecord::Base
  belongs_to :like
  belongs_to :user
  attr_accessible :like, :user
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
   before_filter :authenticate, :except => [:index, :show]

  def authenticate
    if current_user.nil?
      redirect_to login_path, :notice => "Please login."
    end
  end

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foods }
    end
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @food = Food.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/new
  # GET /foods/new.json
  def new
    @food = Food.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @food }
    end
  end

  # GET /foods/1/edit
  def edit
    @food = Food.find(params[:id])
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(params[:food])
    @food.main_user = current_user
    user_foodship = UserFoodship.create(user: current_user, food: @food)
    like = Like.create(food: @food, count: 0)
    if params[:food_categories]
      params[:food_categories].each do |category_id, val|
        FoodFoodCategoryship.create( food_id: @food.id, food_category_id: category_id.to_i)
      end
    end

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render json: @food, status: :created, location: @food }
      else
        format.html { render action: "new" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foods/1
  # PUT /foods/1.json
  def update
    @food = Food.find(params[:id])

    respond_to do |format|
      if @food.update_attributes(params[:food])
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food = Food.find(params[:id])
    @cookbooks = Cookbook.find_all_by_food_id(@food.id)
    if @cookbooks
      @cookbooks.each do |cookbook|
        cookbook.destroy
      end
    end
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/foods/_food_like_comment.html.erb
<div class='food_like_comment' >
  <!-- food likes link -->
  <% if current_user %>
  <% if current_user.already_likes?(food) %>
  <span class='glyphicon glyphicon-heart'></span>
  <%= link_to "已喜欢 (#{food.like.count})", like_path(food.like), id: "food_like_#{food.id}", method: :put, remote: true %>
  <% else %>
  <span class='glyphicon glyphicon-heart'></span>
  <%= link_to "喜欢 (#{food.like.count})", like_path(food.like), id: "food_like_#{food.id}", method: :put, remote: true %>
  <% end %>
  <% else %>
  <span class='glyphicon glyphicon-heart'></span>
  <%= link_to "喜欢 (#{food.like.count})", login_path %>
  <% end %>
  <!-- comments -->
  &nbsp;
  <span class='glyphicon glyphicon-comment'></span>
  <a href="javascript:void(0);" id="comment_<%= food.id %>">评论
    <% if food.comments.count != 0 %>
    <span id="comments_count_<%= food.id %>">(<%= food.comments.count %>)</span>
    <% end %>
  </a>
</div>

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %> 
<% if @food.errors.any? %>  
<div id="error_explanation">
  <h2>
    <%= pluralize(@food.errors.count, "error") %>prohibited this food from being saved:</h2>
  <ul>
    <% @food.errors.full_messages.each do |msg| %>  
    <li>
      <%= msg %></li>
    <% end %></ul>
</div>
<% end %>
  <div class='row'>
    <div class='col-md-3'>
      <div class="field">
        <h3>美食名</h3><br />
        <%= f.text_field :name, class: 'form-control' %></div>
      <div class="field">
        <h3>美食描述</h3><br />
        <%= f.text_area :description, class: 'form-control' %></div>
      <div class="field">
        <h3>美食图片地址</h3><br />
        <%= f.text_field :image_url, class: 'form-control' %></div>
    </div>
    <div class="category_tags col-md-5">
      <h3>美食标签</h3>
      <% FoodCategory.all.each do |category| %>
      <label class='checkbox'>
        <input type='checkbox' name="food_categories[<%= category.id %>]">
        <%= category.name %></label>
      <% end %></div>
  </div>
  <%= submit_tag 'Create Food', class: 'btn btn-lg btn-primary', role: 'button' %>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<div class='container'>
  <h2>精选  美食</h2>
  <hr class="title-divider">
  <div class="row">
    <% 4.times do |tmp| %>
    <div class="col-md-3">
      <% @foods.each do |food| %>
        <% if (food.id - @foods.first.id) % 4 == tmp %>
          <div class='food' id="food_<%= food.id %>">
            <div class='food_img'>
              <%= image_tag food.image_url %></div>
            <div class='food_info'>
              <div class='food_name'><strong><%= link_to food.name, food %></strong></div>
              <div>
                简介：
                <%= food.description %></div>
              <% categories = FoodFoodCategoryship.find_all_by_food_id(food.id) %>
              <% users = UserFoodship.find_all_by_food_id(food.id) %>
              <% if categories.count != 0 %>
              <div>
                标签：
                <% categories.each do |food_categoryship| %>
                <%= FoodCategory.find(food_categoryship.food_category_id).name %>
                <% end %></div>
              <% end %>
              <% if users.count != 0 %>
              <div>
                作者：
                <% users.each do |user_foodship| %>
                <%= User.find(user_foodship.user_id).name %>
                <% end %></div>
              <% end %>
              <!-- user info -->
              <% if food.main_user %>
                <div class='food_main_user_info'>
                  <%= render food.main_user %> 发布于 <%= time_ago_in_words food.created_at %> 以前
                </div>
              <% end %>
              <!-- food like -->
              <div class='food_like_comment_div'>
                <% if food.main_user == current_user %>
                  <%= link_to "删除", food, method: :delete, data: { confirm: "确定删除？所有相关菜谱也会被一并删除！" } %>
                <% end %>
                <%= render partial: 'food_like_comment', locals: { food: food } %>
              </div>
              <!-- comments -->
              <div class= 'list_comments', id="list_comments_<%= food.id %>">
                <div id="existing_comments_<%= food.id %>" >
                  <%= render food.comments %>
                </div>
              </div>
              <div class="new_comment new_comment_<%= food.id %>">
                <%= form_for [food, Comment.new],
                  html: { id: "new_comment_on_#{food.id}" },
                  remote: true do |f| %>
                  <p>
                    <%= f.text_area :content, class: 'form-control', rows: 5 %></p>
                  <p>
                    <%= submit_tag '评论', class: 'btn', role: 'button' %></p>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
  <%= link_to '新美食', new_food_path, class: 'btn btn-lg btn-primary', role: 'button' %></div>

app/views/foods/new.html.erb
<div class='container'>
	<div class='page-header'>
		<h1>新增美食</h1>
	</div>
	<%= render 'form', style: 'margin: 0 auto;' %>
</div>

app/views/foods/show.html.erb
<div class='container food'>
  <div class='row'>
    <div class='col-lg-12'>
      <h2><%= @food.name %></h2>
      <p><%= @food.description %></p>
    </div>
  </div>
  <hr>
  <div class="row food_detail">
    <div class="col-lg-8">
      <h3>简介</h3>
      <p><%= simple_format @food.detail %></p>
      <h3>标签</h3>
      <p>
	  	  <% categories = FoodFoodCategoryship.find_all_by_food_id(@food.id) %>
	    	<% if categories.count != 0 %>
	      	<% categories.each do |food_categoryship| %>
	        	<%= FoodCategory.find(food_categoryship.food_category_id).name %>
		      <% end %>
		    <% else %>
		      <span>暂无标签</span>
	    	<% end %>
			</p>
      <h3>用户评论</h3>
      <!-- food like -->
      <div class='food_like_comment_div'>
        <%= render partial: 'food_like_comment', locals: { food: @food } %>
      </div>
      <!-- comments -->
      <div class= 'list_comments', id="list_comments_<%= @food.id %>">
        <div id="existing_comments_<%= @food.id %>" >
          <%= render @food.comments %>
        </div>
        <div class="new_comment new_comment_<%= @food.id %>">
          <%= form_for [@food, Comment.new],
            html: { id: "new_comment_on_#{@food.id}" },
            remote: true do |f| %>
            <p>
              <%= f.text_area :content, class: 'form-control', rows: 5 %></p>
            <p>
              <%= submit_tag '评论', class: 'btn', role: 'button' %></p>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
  		<%= image_tag @food.image_url, class: 'food_image' %>
  		<h4><%= @food.name %></h4>
    </div>
  </div>
</div>