config/routes.rb
Taotie::Application.routes.draw do

  put 'likes/:id' => 'likes#update', as: 'like'
  put 'cookbook_likes/:id' => 'cookbook_likes#update', as: 'cookbook_like'

  resources :restaurants

  get 'about' => 'welcome#about'

  resources :menus

  resources :materials

  resources :cookbooks do
    resources :cookbook_comments
  end

  resources :foods do
    resources :comments
  end

  resources :users

  get 'signup' => 'users#new', as: 'signup'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  post 'sessions' => 'sessions#create'
  delete 'sessions/:id' => 'sessions#destroy'

  root :to => 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :food
  attr_accessible :content, :user, :food
  validates_presence_of :content
  validates :content, length: {minimum: 10}
  validates :content, format: { without: /fuck/ }

end

app/models/cook_step.rb
class CookStep < ActiveRecord::Base
  belongs_to :cookbook
  attr_accessible :description, :image_url
end

app/models/cookbook.rb
class Cookbook < ActiveRecord::Base
  attr_accessible :description, :difficulty_level, :time_level, :tips, :user, :food_id
  belongs_to :user
  belongs_to :food
  has_many :cook_steps
  has_many :materials
  has_many :menu_cookbookships
  has_many :menus, through: :menu_cookbookships

  has_one :cookbook_like
  has_many :cookbook_comments

	validates_presence_of :description
  validates_presence_of :difficulty_level
  validates_presence_of :time_level
end

app/models/cookbook_comment.rb
class CookbookComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :cookbook
  attr_accessible :content, :user, :cookbook
  validates_presence_of :content
  validates :content, length: {minimum: 10}
  validates :content, format: { without: /fuck/ }

end

app/models/cookbook_like.rb
class CookbookLike < ActiveRecord::Base
  belongs_to :cookbook
  attr_accessible :count, :cookbook
  has_many :user_cookbook_likeships
  has_many :users, through: :user_cookbook_likeships
end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name, :description, :image_url, :main_user, :detail

  belongs_to :main_user, class_name: 'User', foreign_key: 'main_user_id'

  has_many :user_foodships
  has_many :users, through: :user_foodships

  has_many :food_food_categoryships
  has_many :food_categories, through: :food_food_categoryships

  has_one :like
  has_many :comments
  #image_url
  validates :image_url, allow_blank: true, format: {
    with: /\.(gif|jpg|png|Png|Gif|Jpg)$/,
    message: 'Invalid'}

  validates_presence_of :name
  validates_presence_of :description
end

app/models/food_category.rb
class FoodCategory < ActiveRecord::Base
  attr_accessible :name, :category_id

  validates :name, length: {maximum: 10}

  has_many :food_food_categoryships
  has_many :foods, through: :food_food_categoryships
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :food
  has_many :user_likeships
  has_many :users, through: :user_likeships
  attr_accessible :count, :food
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :cookbook
  attr_accessible :name, :quantity
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :user
  has_many :menu_cookbookships
  has_many :cookbooks, through: :menu_cookbookships
  attr_accessible :description, :name
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :name, :user, :image_url
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation,:image_url, :description
  #email
  validates_uniqueness_of :email
  validates :email, format: {
    with: /^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/,
    message: 'Invalid'}
  #name
  validates_presence_of :name, :email
  validates_uniqueness_of :name
  #password
  validates_presence_of :password_confirmation
  validates_confirmation_of :password, on: :create
  validates_presence_of :password, on: :create
  validates :password, length: {minimum: 6}
  #image_url
  validates :image_url, format: {
    with: /\.(gif|jpg|png|Png|Gif|Jpg)$/,
    message: 'Invalid'}

  def self.authenticate(email, password)
    user = find_by_email_and_password(email, password)
  end
  #food posted by the user
  has_many :user_foodships
  has_many :foods, through: :user_foodships
  #like liked by the user
  has_many :user_likeships
  has_many :likes, through: :user_likeships
  #cookbook_like liked by the user
  has_many :user_cookbook_likeships
  has_many :cookbook_likes, through: :user_cookbook_likeships
  #
  def able_to_modify_food?(food)
    self.foods.find(:all, conditions: ['food_id = ?', food.id]).size != 0
  end
  #
  def already_likes?(food)
    self.likes.find(:all, conditions: ['food_id = ?', food.id]).size != 0
  end
  #
  def already_likes_cookbook?(cookbook)
    self.cookbook_likes.find(:all, conditions: ['cookbook_id = ?', cookbook.id]).size != 0
  end
end

app/models/user_foodship.rb
class UserFoodship < ActiveRecord::Base
  attr_accessible :food, :user
  attr_accessible :food_id, :user_id
  belongs_to :food
  belongs_to :user
end

app/models/user_likeship.rb
class UserLikeship < ActiveRecord::Base
  belongs_to :like
  belongs_to :user
  attr_accessible :like, :user
end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController
  before_filter :authenticate, :except => [:index, :show]

  def authenticate
    if current_user.nil?
      redirect_to login_path, :notice => "Please login."
    end
  end

  # GET /cookbooks
  # GET /cookbooks.json
  def index
    @cookbooks = Cookbook.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cookbooks }
    end
  end

  # GET /cookbooks/1
  # GET /cookbooks/1.json
  def show
    @cookbook = Cookbook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cookbook }
    end
  end

  # GET /cookbooks/new
  # GET /cookbooks/new.json
  def new
    @cookbook = Cookbook.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cookbook }
    end
  end

  # GET /cookbooks/1/edit
  def edit
    @cookbook = Cookbook.find(params[:id])
  end

  # POST /cookbooks
  # POST /cookbooks.json
  def create
    @cookbook = Cookbook.new(params[:cookbook])
    @cookbook.user = current_user
    @cookbook_like = CookbookLike.create( cookbook: @cookbook )
    @cookbook.cookbook_like = @cookbook_like
    respond_to do |format|
      if @cookbook.save
        format.html { redirect_to cookbooks_url, notice: 'Cookbook was successfully created.' }
        format.json { render json: @cookbook, status: :created, location: @cookbook }
      else
        format.html { render action: "new" }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cookbooks/1
  # PUT /cookbooks/1.json
  def update
    @cookbook = Cookbook.find(params[:id])

    respond_to do |format|
      if @cookbook.update_attributes(params[:cookbook])
        format.html { redirect_to @cookbook, notice: 'Cookbook was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cookbook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cookbooks/1
  # DELETE /cookbooks/1.json
  def destroy
    @cookbook = Cookbook.find(params[:id])
    @cookbook.destroy

    respond_to do |format|
      format.html { redirect_to cookbooks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cookbooks/_cookbook.html.erb
<div class='cookbook' id="cookbook_<%= cookbook.id %>">
  <div class='cookbook_img'>
    <%= image_tag cookbook.food.image_url %></div>
  <div class='cookbook_info'>
    <div class='food_name'><strong><%= link_to cookbook.food.name + " By " + cookbook.user.name, '#' %></strong></div>
    <div>
      简介：
      <%= cookbook.description %></div>
    <% categories = FoodFoodCategoryship.find_all_by_food_id(cookbook.food.id) %>
    <% if categories.count != 0 %>
      <div>
        标签：
        <% categories.each do |food_food_categoryship| %>
        <%= FoodCategory.find(food_food_categoryship.food_category_id).name %>
        <% end %></div>
    <% end %>
    <div>
      小贴士：
      <%= cookbook.tips %></div>
    <!-- user info -->
    <div class='cookbook_user_info'>
      <%= render cookbook.user %> 发布于 <%= time_ago_in_words cookbook.created_at %> 以前</div>
      <!-- food like -->
    <div class='cookbook_like_comment_div'>
      <% if cookbook.user == current_user %>
        <%= link_to "删除", cookbook, method: :delete, data: { confirm: "确定删除？" } %>
      <% end %>
      <%= render partial: 'cookbook_like_comment', locals: { cookbook: cookbook } %>
    </div>
    <!-- comments -->
    <div class= 'list_cookbook_comments', id="list_cookbook_comments_<%= cookbook.id %>">
      <div id="existing_cookbook_comments_<%= cookbook.id %>" >
        <%= render cookbook.cookbook_comments %>
      </div>
    </div>
    <div class="new_comment new_comment_<%= cookbook.id %>">
      <%= form_for [cookbook, CookbookComment.new],
        html: { id: "new_comment_on_#{cookbook.id}" },
        remote: true do |f| %>
        <p>
          <%= f.text_area :content, class: 'form-control', rows: 5 %></p>
        <p>
          <%= submit_tag '评论', class: 'btn', role: 'button' %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/cookbooks/_cookbook_like_comment.html.erb
<div class='cookbook_like_comment' >
  <!-- cookbook likes link -->
  <% if current_user %>
    <% if current_user.already_likes_cookbook?(cookbook) %>
      <span class='glyphicon glyphicon-heart'></span>
      <%= link_to "已喜欢 (#{cookbook.cookbook_like.count})", cookbook_like_path(cookbook.cookbook_like), id: "cookbook_like_#{cookbook.id}", method: :put, remote: true %>
    <% else %>
      <span class='glyphicon glyphicon-heart'></span>
      <%= link_to "喜欢 (#{cookbook.cookbook_like.count})", cookbook_like_path(cookbook.cookbook_like), id: "cookbook_like_#{cookbook.id}", method: :put, remote: true %>
    <% end %>
  <% else %>
    <span class='glyphicon glyphicon-heart'></span>
    <%= link_to "喜欢 (#{cookbook.cookbook_like.count})", login_path %>
  <% end %>
  <!-- comments -->
  &nbsp;
  <span class='glyphicon glyphicon-comment'></span>
  <a href="javascript:void(0);" id="comment_<%= cookbook.id %>">评论
    <% if cookbook.cookbook_comments.count != 0 %>
    <span id="comments_count_<%= cookbook.id %>">(<%= cookbook.cookbook_comments.count %>)</span>
    <% end %>
  </a>
</div>

app/views/cookbooks/_form.html.erb
<%= form_for(@cookbook) do |f| %> 
<% if @cookbook.errors.any? %>  
<div id="error_explanation">
  <h2>
    <%= pluralize(@cookbook.errors.count, "error") %>prohibited this cookbook from being saved:</h2>
  <ul>
    <% @cookbook.errors.full_messages.each do |msg| %>  
    <li>
      <%= msg %></li>
    <% end %></ul>
</div>
<% end %>
  <div class='row'>
    <div class='col-md-3'>
      <div class="field">
        <h3>所属美食</h3>
        <%= collection_select :cookbook, :food_id, Food.find(:all), :id, :name %>
      </div>
      <div class="field">
        <h3>菜谱难度等级</h3><br />
        <ul class="list-group">
          <li class="list-group-item">
            <input type="radio" name="cookbook[difficulty_level]" value="1">低难度
          </li>
          <li class="list-group-item">
            <input type="radio" name="cookbook[difficulty_level]" value="2">中等难度
          </li>
          <li class="list-group-item">
            <input type="radio" name="cookbook[difficulty_level]" value="3">高难度
          </li>
        </ul>
      </div>
    </div>
    <div class='col-md-3'>
      <div class='field'>
        <h3>菜谱用时</h3><br />
        <ul class="list-group">
          <li class="list-group-item">
            <input type="radio" name="cookbook[time_level]" value="1">少于十分钟
          </li>
          <li class="list-group-item">
            <input type="radio" name="cookbook[time_level]" value="2">十分钟到半小时
          </li>
          <li class="list-group-item">
            <input type="radio" name="cookbook[time_level]" value="3">半小时到一个小时
          </li>
          <li class="list-group-item">
            <input type="radio" name="cookbook[time_level]" value="3">一个小时以上
          </li>
        </ul>
      </div>
      <div class="field">
        <h3>菜谱描述</h3><br />
        <%= f.text_field :description, class: 'form-control' %></div>
      <div class="field">
        <h3>菜谱小贴士</h3><br />
        <%= f.text_field :tips, class: 'form-control' %></div>
    </div>
  </div>
  <div class='row'>
    <%= submit_tag 'Create cookbook', class: 'btn btn-lg btn-primary', role: 'button' %>
  </div>
<% end %>

app/views/cookbooks/edit.html.erb
<h1>Editing cookbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @cookbook %> |
<%= link_to 'Back', cookbooks_path %>

app/views/cookbooks/index.html.erb
<div class='container'>
  <h2>精选  菜谱</h2>
  <hr class="title-divider">
  <div class="row">
    <% 4.times do |tmp| %>
    <div class="col-md-3">
      <% @cookbooks.each do |cookbook| %>
        <% if (cookbook.id - @cookbooks.first.id) % 4 == tmp %>
          <%= render cookbook %>
        <% end %>
      <% end %>
    </div>
    <% end %>
  </div>
  <%= link_to '新菜谱', new_cookbook_path, class: 'btn btn-lg btn-primary', role: 'button' %></div>

app/views/cookbooks/new.html.erb
<div class='container'>
	<div class='page-header'>
		<h1>新增菜谱</h1>
	</div>
	<%= render 'form', style: 'margin: 0 auto;' %>
</div>

app/views/cookbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @cookbook.user %>
</p>

<p>
  <b>Difficulty level:</b>
  <%= @cookbook.difficulty_level %>
</p>

<p>
  <b>Time level:</b>
  <%= @cookbook.time_level %>
</p>

<p>
  <b>Description:</b>
  <%= @cookbook.description %>
</p>

<p>
  <b>Tips:</b>
  <%= @cookbook.tips %>
</p>


<%= link_to 'Edit', edit_cookbook_path(@cookbook) %> |
<%= link_to 'Back', cookbooks_path %>