config/routes.rb
Taotie::Application.routes.draw do

  put 'likes/:id' => 'likes#update', as: 'like'
  put 'cookbook_likes/:id' => 'cookbook_likes#update', as: 'cookbook_like'

  resources :restaurants

  get 'about' => 'welcome#about'

  resources :menus

  resources :materials

  resources :cookbooks do
    resources :cookbook_comments
  end

  resources :foods do
    resources :comments
  end

  resources :users

  get 'signup' => 'users#new', as: 'signup'
  get 'login' => 'sessions#new', as: 'login'
  get 'logout' => 'sessions#destroy', as: 'logout'
  post 'sessions' => 'sessions#create'
  delete 'sessions/:id' => 'sessions#destroy'

  root :to => 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :food
  attr_accessible :content, :user, :food
  validates_presence_of :content
  validates :content, length: {minimum: 10}
  validates :content, format: { without: /fuck/ }

end

app/models/cook_step.rb
class CookStep < ActiveRecord::Base
  belongs_to :cookbook
  attr_accessible :description, :image_url
end

app/models/cookbook.rb
class Cookbook < ActiveRecord::Base
  attr_accessible :description, :difficulty_level, :time_level, :tips, :user, :food_id
  belongs_to :user
  belongs_to :food
  has_many :cook_steps
  has_many :materials
  has_many :menu_cookbookships
  has_many :menus, through: :menu_cookbookships

  has_one :cookbook_like
  has_many :cookbook_comments

	validates_presence_of :description
  validates_presence_of :difficulty_level
  validates_presence_of :time_level
end

app/models/cookbook_comment.rb
class CookbookComment < ActiveRecord::Base
  belongs_to :user
  belongs_to :cookbook
  attr_accessible :content, :user, :cookbook
  validates_presence_of :content
  validates :content, length: {minimum: 10}
  validates :content, format: { without: /fuck/ }

end

app/models/cookbook_like.rb
class CookbookLike < ActiveRecord::Base
  belongs_to :cookbook
  attr_accessible :count, :cookbook
  has_many :user_cookbook_likeships
  has_many :users, through: :user_cookbook_likeships
end

app/models/food.rb
class Food < ActiveRecord::Base
  attr_accessible :name, :description, :image_url, :main_user, :detail

  belongs_to :main_user, class_name: 'User', foreign_key: 'main_user_id'

  has_many :user_foodships
  has_many :users, through: :user_foodships

  has_many :food_food_categoryships
  has_many :food_categories, through: :food_food_categoryships

  has_one :like
  has_many :comments
  #image_url
  validates :image_url, allow_blank: true, format: {
    with: /\.(gif|jpg|png|Png|Gif|Jpg)$/,
    message: 'Invalid'}

  validates_presence_of :name
  validates_presence_of :description
end

app/models/food_category.rb
class FoodCategory < ActiveRecord::Base
  attr_accessible :name, :category_id

  validates :name, length: {maximum: 10}

  has_many :food_food_categoryships
  has_many :foods, through: :food_food_categoryships
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :food
  has_many :user_likeships
  has_many :users, through: :user_likeships
  attr_accessible :count, :food
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :cookbook
  attr_accessible :name, :quantity
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :user
  has_many :menu_cookbookships
  has_many :cookbooks, through: :menu_cookbookships
  attr_accessible :description, :name
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user
  attr_accessible :description, :name, :user, :image_url
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation,:image_url, :description
  #email
  validates_uniqueness_of :email
  validates :email, format: {
    with: /^([a-z0-9_\.-]+)@([\da-z\.-]+)\.([a-z\.]{2,6})$/,
    message: 'Invalid'}
  #name
  validates_presence_of :name, :email
  validates_uniqueness_of :name
  #password
  validates_presence_of :password_confirmation
  validates_confirmation_of :password, on: :create
  validates_presence_of :password, on: :create
  validates :password, length: {minimum: 6}
  #image_url
  validates :image_url, format: {
    with: /\.(gif|jpg|png|Png|Gif|Jpg)$/,
    message: 'Invalid'}

  def self.authenticate(email, password)
    user = find_by_email_and_password(email, password)
  end
  #food posted by the user
  has_many :user_foodships
  has_many :foods, through: :user_foodships
  #like liked by the user
  has_many :user_likeships
  has_many :likes, through: :user_likeships
  #cookbook_like liked by the user
  has_many :user_cookbook_likeships
  has_many :cookbook_likes, through: :user_cookbook_likeships
  #
  def able_to_modify_food?(food)
    self.foods.find(:all, conditions: ['food_id = ?', food.id]).size != 0
  end
  #
  def already_likes?(food)
    self.likes.find(:all, conditions: ['food_id = ?', food.id]).size != 0
  end
  #
  def already_likes_cookbook?(cookbook)
    self.cookbook_likes.find(:all, conditions: ['cookbook_id = ?', cookbook.id]).size != 0
  end
end

app/models/user_foodship.rb
class UserFoodship < ActiveRecord::Base
  attr_accessible :food, :user
  attr_accessible :food_id, :user_id
  belongs_to :food
  belongs_to :user
end

app/models/user_likeship.rb
class UserLikeship < ActiveRecord::Base
  belongs_to :like
  belongs_to :user
  attr_accessible :like, :user
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @materials }
    end
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
    @material = Material.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @material }
    end
  end

  # GET /materials/new
  # GET /materials/new.json
  def new
    @material = Material.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @material }
    end
  end

  # GET /materials/1/edit
  def edit
    @material = Material.find(params[:id])
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(params[:material])

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render json: @material, status: :created, location: @material }
      else
        format.html { render action: "new" }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /materials/1
  # PUT /materials/1.json
  def update
    @material = Material.find(params[:id])

    respond_to do |format|
      if @material.update_attributes(params[:material])
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material = Material.find(params[:id])
    @material.destroy

    respond_to do |format|
      format.html { redirect_to materials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/materials/_form.html.erb
<%= form_for(@material) do |f| %>
  <% if @material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% @material.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cookbook %><br />
    <%= f.text_field :cookbook %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing material</h1>

<%= render 'form' %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<h1>Listing materials</h1>

<table>
  <tr>
    <th>Cookbook</th>
    <th>Name</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @materials.each do |material| %>
  <tr>
    <td><%= material.cookbook %></td>
    <td><%= material.name %></td>
    <td><%= material.quantity %></td>
    <td><%= link_to 'Show', material %></td>
    <td><%= link_to 'Edit', edit_material_path(material) %></td>
    <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New material</h1>

<%= render 'form' %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cookbook:</b>
  <%= @material.cookbook %>
</p>

<p>
  <b>Name:</b>
  <%= @material.name %>
</p>

<p>
  <b>Quantity:</b>
  <%= @material.quantity %>
</p>


<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>